### ISSUE TITLE
Button styles aren't visible in iPhone browser

### ISSUE THREAD

**Issue by pderksen** [gumroad/wp-gumroad#1]
Seems to work on the desktop if you shrink the browser to mobile width, but not on the iPhone itself (Chrome & Safari).

![gumroad mobile styles gone jul 28 9 49 56 am cropped](https://cloud.githubusercontent.com/assets/79667/3915935/536fbc72-236e-11e4-8c60-133eee9e86b3.png)

Reported by user:
http://wordpress.org/support/topic/what-features-would-you-like-to-see?replies=4

**Comment by slavingia** [comment]
Should be fixed now.
