### ISSUE TITLE
Missing git tag in the repository

### ISSUE THREAD

**Issue by sharang-d** [gumroad/wp-gumroad#12]
The latest version as per https://wordpress.org/plugins/gumroad is 1.1.9 but I don't see it in the repository.

![wp-gumroad 2018-11-01 13-19-56](https://user-images.githubusercontent.com/1948197/47839482-e33e8580-ddd8-11e8-860c-bbfed027d090.png)

**Comment by slavingia** [comment]
added, was inaccurate.
