### ISSUE TITLE
Specify a redirect URL after successful payment?

### ISSUE THREAD

**Issue by pderksen** [gumroad/wp-gumroad#2]
Would be nice to have this redirect URL option. Maybe one for payment failure also?

Suggested by user:
http://wordpress.org/support/topic/how-to-provide-a-callback-a-redirect-to-a-thankyou-page?replies=3

**Comment by slavingia** [comment]
we have custom delivery feature now, that will suffice. think there's a way to integrate it better with a proper redirect but will require webapp changes so will close this for now.

cc @karloscarweber
