### ISSUE TITLE
Push new version

### ISSUE THREAD

**Issue by slavingia** [gumroad/wp-gumroad#22]

**Comment by slavingia** [comment]
@karloscarweber are there any changes we should make to get the version number and documentation etc right before i ship to wp.org?

**Comment by karloscarweber** [comment]
I'm honestly not sure how the Wordpress plugin directory gets those version numbers. Let me add a fake plugin and fiddle around with it and I'll get back to you.

**Comment by karloscarweber** [comment]
New version Pushed!
