### ISSUE TITLE
Test on WP 5.0

### ISSUE THREAD

**Issue by slavingia** [gumroad/wp-gumroad#23]

**Comment by karloscarweber** [comment]
So, This works but the help guide in the settings is completely inadequate to describe how to add buttons and embeds in the new Gutenberg editor.

But this is also an opportunity because the editor let's us make some built in widgets using the new editor APIs. So that's what we're going to do. 

First on the agenda is getting a button widget to show up in the editor for quickly adding Gumroad links.

**Comment by karloscarweber** [comment]
So I've been going through this extensively and I believe this issue should be split.

Firstly the Plugin works great on Wordpress 5.0, but we need to add some better guidance to the plugin settings page to really show how to use it in the gutenberg editor.

Second I believe we need a new ticket for making gutenberg specific blocks. I've been working extensively on getting the blocks working and ready for wordpress 5.0 but I've run into problems with how the newest version bundles gutenberg library componenets for plugins. Basically, it's a little buggy and sketchy on what you can expect to work for block development from the gutenberg plugin days to the Wordpress 5.0 future.

Additionally the documentation for Blocks seems to be confused as to the best way to develop. Sometimes it suggests ES5 javascript syntax, other times ESNext style syntax. a slightly more complicated build process is required for this plugin development if we're going to reliably ship a build of the plugin with these components working. 

So, recap: 
- Focus on new documentation in the plugin settings for this ticket.
- Open a new ticket to complete the Gutenberg Blocks.

**Comment by slavingia** [comment]
sounds good on docs first

**Comment by slavingia** [comment]
@karloscarweber should we close this too? (have class 4-7, so will be afk but checking frequently on phone fyi)

**Comment by karloscarweber** [comment]
Yes let's close this too.
I'll send you the weekly report after 7.
