### ISSUE TITLE
Make link normal, button optional.

### ISSUE THREAD

**Issue by slavingia** [gumroad/wp-gumroad#25]
Type of product codes:

default -> link, that's it.
can make button -> link that's styled as a button.
can make all links the overlay -> all now opens gumroad overlay (gumroad.js is included)
can make all links the embed -> adds class? and gumroad-embed.js is included

**Comment by slavingia** [comment]
@karloscarweber make sure this PR is merged in first as it affects existing code. we can then make sure they're compatible with 5.0, push that feature. and then we can work on the new blocks feature.

(priority is marked in the issues using the `next` label)

**Comment by slavingia** [comment]
I don't want to make any changes to the Gumroad Js. I think instead we can just say that the embed/overlay will apply universally instead of per link

**Comment by slavingia** [comment]
one day we can rewrite but these pushes to make our wp plugin up to date at first should be as minimal as possible imo.

**Comment by slavingia** [comment]
if your having trouble wrapping your head around this I can write the new docs that would accompany this change and then you can mimic the functionality mentioned?

**Comment by slavingia** [comment]
here are the docs:

https://github.com/gumroad/wp-gumroad/pull/31

the one tricksy bit is that links to gumroad as normal anchor tags should trigger the overlay (so it can be really easy setup, without much work). but shortcodes should default to links unless type="overlay" or type="embed" is specified.

should be a quick task. if it starts getting really hairy to separate out that behavior, ping me asap and i can come up with an alternative. don't want this taking too long so we can move onto grander things!

**Comment by karloscarweber** [comment]
I've replicated this behavior exactly as we've described and this issue should be closed with PR #32.
