### ISSUE TITLE
Gutenberg block has no button styling

### ISSUE THREAD

**Issue by marekhrabe** [gumroad/wp-gumroad#34]
I just saw the first iteration of new Gumroad block! Exciting! :) 

On my site it definitely looks different compared to the gif from email:

![52596366-5c546c80-2e0d-11e9-8fdb-aee380456717](https://user-images.githubusercontent.com/156676/53256279-c56a9880-36c7-11e9-85da-b14062769003.gif)

The button is not styled at all inside the editor (and also allows multiline text, which is probably not desirable). Gutenberg block should visually resemble the resulting page as much as possible. If I don't have this block selected, I cannot tell it from a paragraph of text.

<img width="361" alt="screenshot 2019-02-22 at 17 30 00" src="https://user-images.githubusercontent.com/156676/53256248-b683e600-36c7-11e9-841e-388c11fc9d29.png">

When I view the page, I'm not getting any styling either. Looks just like a normal link where in the gif it looks like a branded Gumroad button. What's wrong?

<img width="291" alt="screenshot 2019-02-22 at 17 35 16" src="https://user-images.githubusercontent.com/156676/53256487-4cb80c00-36c8-11e9-8843-c7b4a78e578b.png">

Any chance to make the user experience closer to a regular button block? It looks like this in the editor, with better accessible URL input and obvious button styling.

<img width="597" alt="screenshot 2019-02-22 at 17 30 26" src="https://user-images.githubusercontent.com/156676/53256537-72ddac00-36c8-11e9-8118-84d70d951bf5.png">

Code for the core Button block is here: https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/button

Let me know if I can help :)

**Comment by karloscarweber** [comment]
@marekhrabe Thanks for opening an issue!

The Block allows the user to choose between a displaying a normal link, a button, or an embedded product. Each of these has a distinctly different visual representation on the page. It was thought that keeping the editor style to simply be a text field would help to avoid confusion but perhaps it's caused more.

I haven't tried it yet but I think we can change the visual style of what's rendered to the editor in the `edit` function. If so we'll adopt the core Button block input when a Gumroad style button is chosen, and the normal Rich Text when it's just a link.
