### ISSUE TITLE
"What is my Gumroad product ID?" Link Broken

### ISSUE THREAD

**Issue by BFTrick** [gumroad/wp-gumroad#9]
On the Gumroad settings page (which I think is the only page in this plugin) the "What is my Gumroad product ID?" link takes the user to a YouTube video that's no longer available.

![gumroad_help_ _patrick_s_programming_blog_ _wordpress](https://cloud.githubusercontent.com/assets/1065372/15767937/deefbeda-2909-11e6-9265-fbcec2681333.jpg)

I believe you instead want to link to this docs page that explains everything.
https://help.gumroad.com/11164-Payments/whats-my-product-id

**Comment by pderksen** [comment]
@slavingia Would you be able to make this update since I don't have commit access and it's a quick fix?

@BFTrick Thanks for sending in!
